config/routes.rb
Rails.application.routes.draw do
  root 'sessions#new'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :exchanges, only: [:index, :new, :update, :create]
  resources :user_exchanges, only: [:index]
  resources :users, only: [:new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exchange.rb
class Exchange < ApplicationRecord
  belongs_to :user
  belongs_to :buyer, class_name: "User", optional: true
  enum :exchange_type, {cash_to_virtual: "cash_to_virtual", virtual_to_cash: "virtual_to_cash"}
  enum :status, {available: "available", pending: "pending", completed: "completed"}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :exchanges
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  allow_browser versions: :modern

  def authenticate_user!
    redirect_to login_path, alert: "Debes iniciar sesión primero" unless current_user
  end
end

app/controllers/exchanges_controller.rb
class ExchangesController < ApplicationController
  before_action :authenticate_user!

  def index
    @pending_exchanges = Exchange.where(status: :pending, buyer_id: current_user.id)
    @exchanges = Exchange.where(status: :available).where.not(user_id: current_user.id)
  end

  def show
    @exchange = Exchange.find(params[:id])
  end

  def new
    @exchange = Exchange.new(address: current_user.address)
  end

  def create
    @exchange = current_user.exchanges.build(exchange_params)
    @exchange.status = "available"

    if @exchange.save
      redirect_to exchanges_path, notice: "Oferta creada exitosamente"
    else
      render :new
    end
  end

  def update
    @exchange = Exchange.find(params[:id])
    exchange_params = params.require(:exchange).permit(:status)
    exchange_params = exchange_params.merge(buyer_id: current_user.id) if exchange_params[:status] == "pending"
    @exchange.update(exchange_params)
    redirect_to exchanges_path, notice: "Intercambio iniciado"
  end

  private

  def exchange_params
    params.require(:exchange).permit(:amount, :exchange_type, :address)
  end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @exchanges = Exchange.where(status: :available)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email].downcase)

    
    if user
      log_in user
      redirect_to exchanges_path
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/user_exchanges_controller.rb
class UserExchangesController < ApplicationController
  before_action :authenticate_user!

  def index
    @exchanges = Exchange.where(user_id: current_user.id)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params.merge(password: "123456", password_confirmation: "123456"))
    if @user.save
      log_in @user
      redirect_to exchanges_path
    else
      render 'new'
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to root_path, notice: "Datos actualizados exitosamente"
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :bank_account, :address)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/exchanges_helper.rb
module ExchangesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/exchanges/_exchange.html.erb
<div class="bg-white shadow rounded-lg p-4 mb-4">
  <h2 class="text-xl font-semibold">
    <span class="text-green-500"><%= number_to_currency(exchange.amount, unit: "$ ", precision: 0, delimiter: ".") %></span>
    <%= t("activerecord.attributes.exchange.exchange_type.#{exchange.exchange_type}") %>
  </h2>
  <% if current_user.id == exchange.user.id && exchange.buyer.present? %>
   <p>Interesado: <%= exchange.buyer.name %></p>
  <% elsif current_user.id != exchange.user.id%>
    <p>Ofertante: <%= exchange.user.name %></p>
  <% end %>
  <p>🌍 <%= exchange.address %></p>
  
  <% if exchange.available? && current_user.present? && current_user.id != exchange.user.id%>
    <%= button_to "Intercambiar", exchange_path(exchange, exchange: { status: "pending", buyer_id: current_user.id  }), method: :patch, class: "btn btn-secondary mt-2", data: { turbo_frame: "_top" } %>
  <% elsif  exchange.pending? %>
    <div class="flex justify-between mt-2 space-x-4">
      <%= link_to "Contactar por WhatsApp", "https://wa.me/#{exchange.user.phone}", class: "btn btn-success ", target: "_blank" %>
      <%= button_to "Intercambio concretado", exchange_path(exchange, exchange: { status: "completed" }), method: :patch, class: "btn btn-primary " if current_user.id == exchange.user.id %>
    </div>
  <% end %>
</div>

app/views/exchanges/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Exchanges#create</h1>
  <p>Find me in app/views/exchanges/create.html.erb</p>
</div>

app/views/exchanges/index.html.erb
<div class="bg-gradient-to-r from-blue-100 via-blue-200 to-blue-300 min-h-screen">
  <div class="container mx-auto px-4 py-6">
    <h1 class="text-2xl font-bold mb-6 text-center text-blue-600">Ofertas disponibles</h1>

<div>
      <h1 class="text-2xl font-bold mb-6 text-center text-blue-600">Pendiente de concretar intercambio</h1>

    <%= turbo_frame_tag "pending_exchanges_list" do %>
      <div class="space-y-4 max-h-60 overflow-y-auto">
      <% pending_exchanges = @exchanges.where(status: :pending) %>
      <% if pending_exchanges.any? %>
        <% pending_exchanges.each do |exchange| %>
        <%= render partial: "exchanges/exchange", locals: { exchange: exchange } %>
        <% end %>
      <% else %>
        <p class="text-center text-gray-500">No hay intercambios por concretar.</p>
      <% end %>
      </div>
    <% end %>
    </div>

    <div>
      <h1 class="text-2xl font-bold mb-6 text-center text-blue-600">Posibles intercambios</h1>

      <%= turbo_frame_tag "exchanges_list" do %>
      <div class="space-y-4 max-h-60 overflow-y-auto">
        <% available_exchanges = @exchanges.where(status: :available) %>
        <% if available_exchanges.any? %>
        <% available_exchanges.each do |exchange| %>
          <%= render partial: "exchanges/exchange", locals: { exchange: exchange } %>
        <% end %>
        <% else %>
        <p class="text-center text-gray-500">No hay intercambios disponibles.</p>
        <% end %>
      </div>
      <% end %>
    </div>

    
  </div>
  <div class="fixed bottom-4 justify-between w-full flex space-x-4 px-2">
      <%= link_to "Ver mis ofertas", user_exchanges_path, class: "btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full shadow-lg" %>
      <%= link_to "Nueva oferta", new_exchange_path, class: "btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full shadow-lg" %>
    </div>
</div>

app/views/exchanges/new.html.erb
<div class="bg-gradient-to-r from-blue-100 via-blue-200 to-blue-300 min-h-screen flex items-center justify-center p-4">
  <div class="bg-white rounded-lg shadow-lg p-6 w-full max-w-md">
    <h2 class="text-2xl font-bold mb-6 text-center text-blue-600">Nueva oferta</h2>
    <%= form_with(model: @exchange, local: true) do |f| %>
      <div class="mb-6">
        <%= f.label :amount, "Monto", class: "block text-sm font-medium text-gray-700 mb-2" %>
        <%= f.number_field :amount, step: 0.01, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent placeholder-gray-400" %>
      </div>

      <!-- Campo: Tipo de intercambio -->
      <div class="mb-6">
        <%= f.label :exchange_type, "Tipo de intercambio", class: "block text-sm font-medium text-gray-700 mb-2" %>
        <%= f.select :exchange_type, options_for_select([["Efectivo a virtual", "cash_to_virtual"], ["Virtual a efectivo", "virtual_to_cash"]]), {}, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent" %>
      </div>

      <!-- Campo: Dirección -->
      <div class="mb-6">
        <%= f.label :address, "Dirección", class: "block text-sm font-medium text-gray-700 mb-2" %>
        <%= f.text_field :address, class: "w-full px-4 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-purple-500 focus:border-transparent placeholder-gray-400" %>
      </div>

      <!-- Botón de envío -->
      <div class="text-center">
        <%= f.submit "Crear oferta", class: "w-full bg-purple-600 text-white py-2 px-4 rounded-lg hover:bg-purple-700 focus:outline-none focus:ring-2 focus:ring-purple-500 focus:ring-offset-2 transition-colors" %>
      </div>
    <% end %>
  </div>
</div>

app/views/exchanges/show.html.erb
<div>
  <h1 class="font-bold text-4xl">Exchanges#show</h1>
  <p>Find me in app/views/exchanges/show.html.erb</p>
</div>

app/views/home/index.html.erb
<div class="container mx-auto px-4">
  <h1 class="text-2xl font-bold mb-4">Intercambios disponibles</h1>
  
  <%= turbo_frame_tag "exchanges_list" do %>
    <%= render partial: "exchanges/exchange", collection: @exchanges %>
  <% end %>
  
  <%= link_to "Nueva oferta", new_exchange_path, class: "btn btn-primary", data: { turbo_frame: "modal" } %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Cajero P2p" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
      <%= yield %>
    
  </body>
</html>

app/views/user_exchanges/index.html.erb
<div class="bg-gradient-to-r from-blue-100 via-blue-200 to-blue-300 min-h-screen">
  <div class="container mx-auto px-4 py-6">
    <h1 class="text-2xl font-bold mb-6 text-center text-blue-600">Mis intercambios</h1>

    <div>
      <h2 class="text-2xl font-bold mb-6 text-center text-blue-600">Pendiente de reunirse con interesado</h2>

      <%= turbo_frame_tag "pending_exchanges_list" do %>
      <div class="space-y-4 max-h-60 overflow-y-auto">
        <% pending_exchanges = @exchanges.where(status: :pending) %>
        <% if pending_exchanges.any? %>
        <% pending_exchanges.each do |exchange| %>
          <%= render partial: "exchanges/exchange", locals: { exchange: exchange } %>
        <% end %>
        <% else %>
        <p class="text-center text-gray-500">No hay intercambios por concretar.</p>
        <% end %>
      </div>
      <% end %>
    </div>

    <div>
      <h1 class="text-2xl font-bold mb-6 text-center text-blue-600">Disponibles para los otros usuarios</h1>

      <%= turbo_frame_tag "exchanges_list" do %>
      <% available_exchanges = @exchanges.where(status: :available) %>
        <div class="space-y-4 max-h-60 overflow-y-auto">
          <% if available_exchanges.any? %>
            <% available_exchanges.each do |exchange| %>
              <%= render partial: "exchanges/exchange", locals: { exchange: exchange } %>
            <% end %>
          <% else %>
            <p class="text-center text-gray-500">No hay intercambios disponibles.</p>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
  <div class="fixed bottom-4 justify-between w-full flex space-x-4 px-2">
    <%= link_to "Ver ofertas Disponibles", exchanges_path, class: "btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full shadow-lg" %>
    <%= link_to "Nueva oferta", new_exchange_path, class: "btn btn-primary bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full shadow-lg" %>
  </div>
</div>

app/views/users/create.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#create</h1>
  <p>Find me in app/views/users/create.html.erb</p>
</div>

app/views/users/edit.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#edit</h1>
  <p>Find me in app/views/users/edit.html.erb</p>
</div>

app/views/users/new.html.erb
<div class="bg-gradient-to-r from-blue-100 via-blue-100 to-blue-100 min-h-screen flex items-center justify-center">
    <div class="bg-white p-8 rounded-lg shadow-lg w-full max-w-md">
      
      <h1 class="text-xl font-semibold mb-4 text-blue-600 ">Registrate</h1>
      <%= form_with(model: @user, local: true, class: "space-y-6") do |f| %>
        <div class="field">
          <%= f.label :name, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :name, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
        </div>
        <div class="field">
          <%= f.label :email, class: "block text-sm font-medium text-gray-700" %>
          <%= f.email_field :email, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
        </div>
        <div class="field">
          <%= f.label :address, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :address, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
        </div>
        <div class="field">
          <%= f.label :phone, class: "block text-sm font-medium text-gray-700" %>
          <%= f.text_field :phone, class: "mt-1 block w-full px-4 py-2 border border-gray-300 rounded-md shadow-sm focus:ring-blue-500 focus:border-blue-500" %>
        </div>
        <div class="actions">
          <%= f.submit "Sign up", class: "w-full bg-blue-600 text-white py-2 px-4 rounded-md hover:bg-blue-700 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-offset-2" %>
        </div>
      <% end %>
    </div>
</div>

app/views/users/update.html.erb
<div>
  <h1 class="font-bold text-4xl">Users#update</h1>
  <p>Find me in app/views/users/update.html.erb</p>
</div>